### ISSUE TITLE
AntiBotUltra Issue

### ISSUE THREAD

**Issue by iGodGift** [OfficialAName/AntiBotUltra-1.8-1.9#2]
Well I have a 1.9.2 Spigot Server and while i was on 1.8.8 the antibot ultra worked just fine...Yesterday and after days without antibotultra plugin installed cuz 1.9.2 I found the topic about AntiBotUltra Reborn which works on 1.9 versions..I installed it..and I restarted the server...but no folder showed up on plugins to edit the config...and ingame the /pl couldn't detect the plugin

**Comment by OfficialAName** [comment]
please send me your server log!

**Comment by iGodGift** [comment]
[01:46:16] [Server thread/INFO]: Starting minecraft server version 1.9.2
[01:46:16] [Server thread/INFO]: Loading properties
[01:46:16] [Server thread/WARN]: ressource-pack-hash is depricated and found along side resource-pack-sha1. resource-pack-hash will be ignored.
[01:46:16] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[01:46:16] [Server thread/INFO]: Default game type: SURVIVAL
[01:46:16] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a1b8bf3-f326992 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
[01:46:16] [Server thread/INFO]: Server Ping Player Sample Count: 12
[01:46:16] [Server thread/INFO]: Using 4 threads for Netty based IO
[01:46:16] [Server thread/INFO]: Debug logging is disabled
[01:46:16] [Server thread/INFO]: Generating keypair
[01:46:16] [Server thread/INFO]: Starting Minecraft server on 5.62.98.60:25565
[01:46:16] [Server thread/INFO]: Using epoll channel type
[01:46:16] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[01:46:16] [Server thread/ERROR]: Could not load 'plugins/AntiBot-Ultra.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: aname/antibotultra/light/a/A : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: aname/antibotultra/light/a/A : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-a1b8bf3-f326992]
	... 6 more

**Comment by OfficialAName** [comment]
Please use Java 8 to fix your problem, and if you can't, I will send you a link with the Java 7 Plugin!

**Comment by iGodGift** [comment]
I've tryed switching to Java 8 and it didnt worked at all

**Comment by OfficialAName** [comment]
As your log is saying : "at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]" it means you are running on java 7, please, I tell you again, USE Java 8, as I tested myself that it won't work on java 7 because it is outdated and downgrading to Java 7 it would be a pain in the ass for Developers!

**Comment by iGodGift** [comment]
Okay I tryed once again and it worked now...I dont know what happened earlier but when you said switch to Java 8 I did as you said and it didnt worked...after i noticed an update from spigot and I tryed again it worked...thanks for your help anyways.
